controller_list:
  - name: fake_right_arm_controller
    joints:
      - base_link1
      - joint1_R
      - joint2_R
      - joint3_R
      - joint4_R
      - joint5_R
      - joint6_R
  - name: fake_left_arm_controller
    joints:
      - base_link1
      - joint1_L
      - joint2_L
      - joint3_L
      - joint4_L
      - joint5_L
      - joint6_L
  - name: fake_waist_controller
    joints:
      - base_link1
  - name: fake_all_controller
    joints:
      - base_link1
      - joint1_L
      - joint2_L
      - joint3_L
      - joint4_L
      - joint5_L
      - joint6_L
      - joint1_R
      - joint2_R
      - joint3_R
      - joint4_R
      - joint5_R
      - joint6_R