# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: init_right
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link1
    - joint1_L
    - joint2_L
    - joint3_L
    - joint4_L
    - joint5_L
    - joint6_L
    - joint1_R
    - joint2_R
    - joint3_R
    - joint4_R
    - joint5_R
    - joint6_R
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: plan_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link1
      - joint1_L
      - joint2_L
      - joint3_L
      - joint4_L
      - joint5_L
      - joint6_L
      - joint1_R
      - joint2_R
      - joint3_R
      - joint4_R
      - joint5_R
      - joint6_R
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link1
      - joint1_R
      - joint2_R
      - joint3_R
      - joint4_R
      - joint5_R
      - joint6_R
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link1
      - joint1_L
      - joint2_L
      - joint3_L
      - joint4_L
      - joint5_L
      - joint6_L
  - name: both_arms_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link1
      - joint1_L
      - joint2_L
      - joint3_L
      - joint4_L
      - joint5_L
      - joint6_L
      - joint1_R
      - joint2_R
      - joint3_R
      - joint4_R
      - joint5_R
      - joint6_R
  - name: waist_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      []
  - name: all_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link1
      - joint1_L
      - joint2_L
      - joint3_L
      - joint4_L
      - joint5_L
      - joint6_L
      - joint1_R
      - joint2_R
      - joint3_R
      - joint4_R
      - joint5_R
      - joint6_R